const crypto = require("crypto");
const PDFDocument = require("pdfkit");
const { uploadToR2 } = require("./cloudflareR2");

function hmacSignature(payload, secret) {
  return crypto.createHmac("sha256", secret).update(payload).digest("hex");
}

function generateSoundLicensePdfBuffer({ license, sound, buyer, creator, template }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "LETTER",
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
      });

      const buffers = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      doc.fontSize(24).font("Helvetica-Bold").text("MACADAM CO.", { align: "center" }).moveDown();
      doc.fontSize(18).font("Helvetica").text("SOUND LICENSE CERTIFICATE", { align: "center" }).moveDown(2);

      doc.fontSize(12).font("Helvetica-Bold").text("License ID:");
      doc.font("Helvetica").text(String(license._id)).moveDown();

      doc.font("Helvetica-Bold").text("License Number:");
      doc.font("Helvetica").text(license.licenseNumber).moveDown();

      doc.font("Helvetica-Bold").text("License Type:");
      doc.font("Helvetica").text(template?.licenseType || license.licenseType).moveDown();

      doc.font("Helvetica-Bold").text("Issued At:");
      doc.font("Helvetica").text(new Date(license.createdAt || Date.now()).toISOString()).moveDown();

      if (license.expiresAt) {
        doc.font("Helvetica-Bold").text("Expires At:");
        doc.font("Helvetica").text(new Date(license.expiresAt).toISOString()).moveDown();
      }

      doc.moveDown();
      doc.fontSize(14).font("Helvetica-Bold").text("LICENSED SOUND");
      doc.moveDown(0.5).fontSize(12).font("Helvetica");
      doc.text(`Title: ${sound.title}`);
      doc.text(`File Hash (SHA-256): ${license.soundHash || sound.audio?.audioHash || ""}`);
      doc.text(`Story IP ID: ${license.storyFoundationId || sound.storyFoundation?.storyFoundationId || ""}`);
      doc.moveDown();

      doc.fontSize(14).font("Helvetica-Bold").text("LICENSOR (CREATOR)");
      doc.moveDown(0.5).fontSize(12).font("Helvetica");
      doc.text(`Account ID: ${String(creator._id)}`);
      doc.text(`Name: ${creator.userName || creator.email}`);
      doc.text(`Email: ${creator.email}`);
      doc.moveDown();

      doc.fontSize(14).font("Helvetica-Bold").text("LICENSEE (BUYER)");
      doc.moveDown(0.5).fontSize(12).font("Helvetica");
      doc.text(`Account ID: ${String(buyer._id)}`);
      doc.text(`Name: ${buyer.userName || buyer.email}`);
      doc.text(`Email: ${buyer.email}`);
      doc.moveDown();

      doc.fontSize(14).font("Helvetica-Bold").text("TERMS SNAPSHOT");
      doc.moveDown(0.5).fontSize(11).font("Helvetica");
      doc.text(`Territory: ${license.terms?.territory || "worldwide"}`);
      doc.text(
        `Duration: ${
          license.terms?.durationType === "time_based"
            ? `${license.terms?.durationDays || ""} days`
            : "perpetual"
        }`
      );
      doc.text(`Exclusive: ${license.terms?.exclusivity ? "Yes" : "No"}`);
      doc.text(`Attribution Required: ${license.terms?.attributionRequired ? "Yes" : "No"}`);
      doc.text(`Resale Allowed: No`);
      doc.moveDown();

      if (license.terms?.legalText) {
        doc.fontSize(12).font("Helvetica-Bold").text("Legal Text:");
        doc.font("Helvetica").fontSize(10).text(license.terms.legalText, { align: "justify" }).moveDown();
      }

      doc.fontSize(12).font("Helvetica-Bold").text("Payment:");
      doc.font("Helvetica").text(`Amount: ${license.price} ${license.currency || "USD"}`);
      doc.font("Helvetica").text(`Stripe Payment Intent: ${license.stripePaymentIntentId || ""}`);
      doc.moveDown();

      doc.fontSize(10).font("Helvetica").text("Generated by MacAdam Co.", { align: "center" });
      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

async function generateAndUploadSoundLicenseCertificates({ license, sound, buyer, creator, template }) {
  const issuedAt = new Date().toISOString();
  const secret = process.env.MACADAM_LICENSE_SIGNATURE_SECRET || "";
  if (!secret) {
    throw new Error("MACADAM_LICENSE_SIGNATURE_SECRET is not configured");
  }

  const licenseJson = {
    licenseId: String(license._id),
    licenseNumber: license.licenseNumber,
    licenseType: template?.licenseType || license.licenseType,
    buyer: { id: String(buyer._id), email: buyer.email, name: buyer.userName || buyer.email },
    creator: { id: String(creator._id), email: creator.email, name: creator.userName || creator.email },
    sound: {
      id: String(sound._id),
      title: sound.title,
      fileUrl: sound.audio?.fileUrl || "",
      fileHash: license.soundHash || sound.audio?.audioHash || "",
      storyFoundationId: license.storyFoundationId || sound.storyFoundation?.storyFoundationId || "",
    },
    scope: {
      usageRights: license.terms?.usageRights || {},
      territory: license.terms?.territory || "worldwide",
      territoryNotes: license.terms?.territoryNotes || "",
      durationType: license.terms?.durationType || "perpetual",
      durationDays: license.terms?.durationDays || null,
      exclusivity: Boolean(license.terms?.exclusivity),
      attributionRequired: Boolean(license.terms?.attributionRequired),
      resaleAllowed: false,
    },
    issuedAt,
    expiresAt: license.expiresAt ? new Date(license.expiresAt).toISOString() : null,
    platform: {
      name: "MacAdam",
      signatureAlg: "HMAC-SHA256",
    },
  };

  const signature = hmacSignature(JSON.stringify(licenseJson), secret);
  licenseJson.platform.signature = signature;

  const jsonBuf = Buffer.from(JSON.stringify(licenseJson, null, 2), "utf8");
  const jsonKeyBuyer = `ip/${buyer._id}/licenses/sounds/${license._id}/license-certificate.json`;
  const jsonUpload = await uploadToR2(jsonBuf, jsonKeyBuyer, "application/json");

  const pdfBuf = await generateSoundLicensePdfBuffer({ license, sound, buyer, creator, template });
  const pdfKeyBuyer = `ip/${buyer._id}/licenses/sounds/${license._id}/license-certificate.pdf`;
  const pdfUpload = await uploadToR2(pdfBuf, pdfKeyBuyer, "application/pdf");

  return {
    licenseJson,
    signature,
    json: jsonUpload,
    pdf: pdfUpload,
  };
}

module.exports = {
  generateAndUploadSoundLicenseCertificates,
};

